name: PR content checks

on:
  pull_request:
    branches:
     - main
    paths:
     - '**.md'

jobs:
  lint_markdown_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      # https://github.com/actions/checkout
      uses: actions/checkout@v2
    - name: Check .md files for syntax errors
      uses: nosborn/github-action-markdown-cli@v3.2.0
      with:
        config_file: ".markdownlint.yaml"
        files: "./docs"
        
  lint_prose:
     # https://github.com/errata-ai/vale-action
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: false
    - name: Lint the docs folder
      uses: errata-ai/vale-action@master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        files: __onlyModified
        onlyAnnotateModifiedLines: true
