name: PR preflight checks

on:
  pull_request:
    types:
      - opened
    branches:
     - main
    paths:
     - '**.md'

jobs:
  lint_markdown_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: false
    - name: Check .md files for syntax errors
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        config_file: ".markdownlint.yaml"
        files: "./docs"
